backend:
  name: git-gateway
  repo: johncwaters/haxs-stack
  branch: master
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://haxs-stack.netlify.app" # your site name
display_url: "https://haxs-stack.netlify.app"

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: post/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: datetime }
      - { label: "Publish", name: "isPublish", widget: "boolean", default: true }
      - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
      - { name: body, label: Body, widget: markdown }
  
  - name: product
    label: Products
    folder: src/content/products
    create: true
    format: frontmatter
    preview_path: product/{{slug}}
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: markdown }
      - { name: media, label: Media, widget: image, allow_multiple: true, media_library: { config: { multiple: true } } }
      - { name: category, label: Category, widget: string }
      - { name: price, label: Price, widget: number, value_type: "float"}
      - { name: compare_at_price, label: Compare-at Price, widget: number, value_type: "float", required: false }
      - { name: track_quantity, label: "Track quantity", widget: boolean, default: true }
      - { name: quantity, label: Quantity, widget: number }
      - { name: continue_selling, label: "Continue selling when out of stock", widget: boolean, default: true }
      - { name: sku, label: SKU, widget: string, required: false }
      - { name: barcode, label: Barcode, widget: string, required: false }
      - { name: physical_product, label: "This is a physical product", widget: boolean, default: true }
      - { name: weight, label: Weight, widget: number }
      - { name: weight_unit, label: "Weight unit", widget: select, options: ["lb", "kg", "oz", "g"] }
      - { name: customs_information, label: "Customs information", widget: string, required: false }
      - { name: variants, label: Variants, widget: list, fields: [
          { name: option, label: "Option", widget: string },
          { name: value, label: "Value", widget: string }
        ]
      }
      - { name: seo_title, label: "SEO Title", widget: string }
      - { name: seo_description, label: "SEO Description", widget: string }
      - { name: product_type, label: "Product type", widget: string }
      - { name: vendor, label: Vendor, widget: string }
      - { name: collections, label: Collections, widget: list, field: { name: collection, label: "Collection", widget: string } }
      - { name: tags, label: Tags, widget: list, field: { name: tag, label: "Tag", widget: string } }
      - { name: theme_template, label: "Theme template", widget: string, default: "Default product" }
